'use client'

import { useEffect, useRef, useState } from 'react'

const AI_PROMPTS = [
  {
    label: 'Walk Cycle (12 frames)',
    url: 'https://image.pollinations.ai/prompt/pixel%20art%20PICO-8%20palette%20walk%20cycle%20animation%20cute%20cat%20sprite%20sheet%204%20frames%20horizontal%2016x16%20each%20frame%20consistent%20character',
  },
  {
    label: 'Walk Cycle 4 frames',
    url: 'https://image.pollinations.ai/prompt/pixel%20art%20PICO-8%20palette%204-frame%20walk%20cycle%20sprite%20sheet%20horizontal%20strip%20of%20a%20cute%20cat%20walking%20animation%2016x16%20each%20frame%20consistent%20legs%20alternating',
  },
  {
    label: 'Walk Cycle 4 frames v2',
    url: 'https://image.pollinations.ai/prompt/pixel%20art%20sprite%20sheet%204%20frames%20walking%20cat%20animation%20PICO-8%20colors%2016x16%20each%20frame%20horizontal%20strip%20legs%20moving%20consistent',
  },
]

export default function PreviewPage() {
  const [loading, setLoading] = useState(true)
  const [imgs, setImgs] = useState<{ loaded: boolean[] }>({ loaded: AI_PROMPTS.map(() => false) })

  return (
    <div style={{
      background: '#0b1120', minHeight: '100dvh',
      color: '#f0f4f8', fontFamily: 'system-ui, sans-serif',
      padding: 20, maxWidth: 800, margin: '0 auto',
    }}>
      <h1 style={{ fontSize: 22, marginBottom: 4 }}>🎬 AI Pixel Art Sprite Sheet Preview</h1>
      <p style={{ color: '#94a5b8', fontSize: 13, marginBottom: 20 }}>
        Generated by Pollinations.ai · PICO-8 pixel art
      </p>

      {AI_PROMPTS.map((item, i) => (
        <div key={i} style={{
          background: '#141b2d', borderRadius: 16, padding: 16, marginBottom: 16,
        }}>
          <h2 style={{ fontSize: 14, marginBottom: 8, color: '#8b5cf6' }}>{item.label}</h2>
          <img
            src={item.url}
            alt={item.label}
            style={{
              width: '100%', height: 'auto', imageRendering: 'pixelated',
              borderRadius: 8, display: 'block',
            }}
            onLoad={() => setLoading(false)}
            onError={() => setLoading(false)}
          />
          {loading && (
            <div style={{ padding: 40, textAlign: 'center', color: '#5a6d85' }}>
              ⏳ Generating...
            </div>
          )}
        </div>
      ))}

      {/* Our sprite sheet comparison */}
      <div style={{
        background: '#141b2d', borderRadius: 16, padding: 16, marginBottom: 16,
      }}>
        <h2 style={{ fontSize: 14, marginBottom: 8, color: '#f59e0b' }}>
          🛠 Manual Edit (base sprite → pixel manipulation)
        </h2>
        <img
          src="/pixel-gen/sprites/0.png?v=v6"
          alt="Base sprite"
          style={{
            width: 128, height: 128, imageRendering: 'pixelated',
            borderRadius: 8, display: 'block', marginBottom: 8,
          }}
        />
        <p style={{ color: '#5a6d85', fontSize: 11 }}>
          Base sprite 0.png · 128×128 · Can be shifted for walk animation
        </p>
      </div>

      {/* How it works */}
      <div style={{
        background: '#141b2d', borderRadius: 16, padding: 16,
      }}>
        <h2 style={{ fontSize: 14, marginBottom: 8, color: '#8b5cf6' }}>點樣產生意見</h2>
        <p style={{ color: '#94a5b8', fontSize: 12, lineHeight: 1.6 }}>
          <strong style={{ color: '#f0f4f8' }}>AI gen sprite sheet</strong> — 用 Pollinations.ai API
          直接生成整條 sprite sheet。好處係快，但 frame 連貫性 depends on prompt。
        </p>
        <p style={{ color: '#94a5b8', fontSize: 12, lineHeight: 1.6, marginTop: 8 }}>
          <strong style={{ color: '#f0f4f8' }}>Manual pixel manipulation</strong> — 用同一張 base sprite
          做 pixel shift / overlay。好處係 100% 連貫，但需要 code 處理每個 species。
        </p>
      </div>
    </div>
  )
}
